name: Build with PyInstaller and Release
on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    permissions:
      contents: write

    strategy:
      matrix:
        os: [windows]

    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Set up uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Build with PyInstaller
        run: |
          uv run pyinstaller main.spec

      - name: Rename Artifacts
        run: |
          mv dist/image-processor-for-shrimp.zip dist/image-processor-for-shrimp-${{ github.ref_name }}-${{ matrix.os }}.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
            files: dist/image-processor-for-shrimp-${{ github.ref_name }}-${{ matrix.os }}.zip
            generate_release_notes: true
